<h1 id="using-errator">Using Errator</h1>
<ol>
<li><a href="#if-you-don-t-read-anything-else-read-this">If you don't ready anything else, READ THIS</a></li>
<li><a href="#errator-s-operation">Errator's operation</a></li>
<li><a href="#capturing-the-narration">Capturing the narration</a></li>
<li><a href="#skipping-decorating-functions">Skipping decorating functions</a></li>
<li><a href="#customizing-the-narration">Customizing the narration</a></li>
<li><a href="#getting-more-details-with-contexts">Getting more details with contexts</a></li>
<li><a href="#advanced-fragment-access">Advanced fragment access</a></li>
<li><a href="#verbose-narrations">Verbose narrations</a></li>
<li><a href="#testing-and-debugging">Testing and debugging</a></li>
<li><a href="#tidying-up-stack-traces">Tidying up stack traces</a></li>
<li><a href="#usage-tips">Usage tips</a></li>
</ol>
<p>Errator is a fairly small library (one file) that's easy to wrap your head around. While basic usage is fairly simple, errator also allows you more sophisticated uses in multi-threaded programs where each thread can have its own exception narration, as well as being able to manage partial narrations.</p>
<p>There are a couple of anti-patterns in errator's use which are important to understand, so we'll lead off with addressing those before launching into a more general discussion on using errator.</p>
<blockquote>
<p><strong>note</strong></p>
<p>The documentation generally discusses decorating functions with errator, but errator's decorators can also be used to decorate methods. For brevity, when 'function' is used it should be assumed to mean 'function or method'.</p>
</blockquote>
<h2 id="if-you-dont-read-anything-else-read-this">If you don't read anything else, READ THIS</h2>
<p>Errator decorators, context managers, and narration management functions work together to manage a set of per-thread stacks of &quot;narration fragments&quot;. In &quot;normally&quot; operating code (that is, with no exceptions), these fragments are created at the start of a function or context, and discarded when the function or context completes without an exception (push on call, pop on return).</p>
<p>But when an exception occurs, the fragment is retained, and as the exception passes un-caught up the stack through other errator managed functions or contexts, additional fragments may also be retained, until the exception is caught and errator is told that it may finally discard the fragments. This discarding may be done automatically or under programmatic control, depending on how errator is to be used, but the key is that unless errator discards the fragments, they will simply keep growing in number and may cause memory issues if code experiences numerous errors without disposing of the fragments, not to mention yielding confusing narrations of exceptions.</p>
<p>There are two anti-patterns that can lead to this situation to be aware of.</p>
<h3 id="anti-pattern-1---catching-the-exception-outside-of-errators-view">Anti-pattern #1-- catching the exception outside of errator's view</h3>
<p>If you catch an exception in a function that hasn't been decorated with errator decorators (and there are no more errator-decorated functions or contexts at a more global level in the call stack), it will leak narration fragments and the narration will grow, making it useless:</p>
<pre class="sourceCode "><code>def f1():
    &quot;NOTE: not decorated with &#39;narrate()&#39;&quot;
    try:
        f2()
    except Exception as e:
        story = get_narration()
        # handle the exception

@narrate(&quot;I starting to &#39;f2&#39;&quot;)
def f2():
    f3()

@narrate(&quot;I&#39;ve been asked to &#39;f3&#39;&quot;)
def f3():
    raise Exception(&quot;catch me!&quot;)

# some time later...
f1()</code></pre>
<p>The problem is that f1() isn't decorated with <code>narrate()</code>, and hence errator doesn't know that the exception was handled. Try it-- enter the above code and call f1() twice, and then look at the returned narration from <code>get_narration()</code>. <strong>Remember</strong>: this isn't a problem if there is an errator decorated function or context at a more global level in the call stack.</p>
<p>You can fix this a couple of ways:</p>
<p><strong>Approach #1:</strong></p>
<pre class="sourceCode "><code># this approach will cause errator to automatically clean fragments:

@narrate(&quot;I&#39;m starting f1&quot;)  # we added decoration to the ``f1()`` function
def f1():
    &quot;NOTE: NOW decorated with &#39;narrate()&#39;&quot;
    try:
        f2()
    except Exception as e:
        story = get_narration()
        # handle the exception

@narrate(&quot;I starting to &#39;f2&#39;&quot;)
def f2():
    f3()

@narrate(&quot;I&#39;ve been asked to &#39;f3&#39;&quot;)
def f3():
    raise Exception(&quot;catch me!&quot;)

# some time later...
f1()</code></pre>
<p><strong>Approach #2</strong></p>
<pre class="sourceCode "><code># in this approach, you manually clear out the narration fragments

def f1():
    &quot;NOTE: no decoration, but we clean up in the exception clause&quot;
    try:
        f2()
    except Exception as e:
        story = get_narration()
        reset_narration()  # CLEANS UP FRAGMENTS
        # handle the exception

@narrate(&quot;I starting to &#39;f2&#39;&quot;)
def f2():
    f3()

@narrate(&quot;I&#39;ve been asked to &#39;f3&#39;&quot;)
def f3():
    raise Exception(&quot;catch me!&quot;)

# some time later...
f1()</code></pre>
<h3 id="anti-pattern-2-shutting-off-automatic-cleanup-but-not-clearing-up-fragments">Anti-pattern #2: Shutting off automatic cleanup but not clearing up fragments</h3>
<p>For more complex uses of errator, you can turn off automatic fragment cleanup, but if you do so then you <strong>must</strong> handle cleanup yourself. The following will suffer from the same leakage/growing narration as the first anti-pattern:</p>
<pre class="sourceCode "><code>@narrate(&quot;Look out-- I&#39;m about to f1()!&quot;)
def f1():
    &quot;we&#39;ve got f1 decorated&quot;
    try:
        f2()
    except Exception as e:
        story = get_narration()
        # handle the exception

@narrate(&quot;I starting to &#39;f2&#39;&quot;)
def f2():
    f3()

@narrate(&quot;I&#39;ve been asked to &#39;f3&#39;&quot;)
def f3():
    raise Exception(&quot;catch me!&quot;)

set_narration_options(auto_prune=False)

# later, in the same thread:
f1()</code></pre>
<p>In this example, even though all functions in the call chain are decorated with <code>narrate()</code>, we'll still leak fragements and allow the narration to grow. This is because <code>set_narration_options()</code> was used to turn off &quot;auto_prune&quot;, which makes errator not discard fragments when exceptions have been handled. Note that this has to happen in the same thread; each thread can have different narration options.</p>
<p>If you want to have auto_prune off (and there are cases where you might want to do this), fixing this is like the second solution to the first anti-pattern:</p>
<pre class="sourceCode "><code>@narrate(&quot;Look out-- I&#39;m about to f1()!&quot;)
def f1():
    &quot;we&#39;ve got f1 decorated&quot;
    try:
        f2()
    except Exception as e:
        story = get_narration()
        reset_narration()         #CLEANS UP THE FRAGMENTS
        # handle the exception

@narrate(&quot;I starting to &#39;f2&#39;&quot;)
def f2():
    f3()

@narrate(&quot;I&#39;ve been asked to &#39;f3&#39;&quot;)
def f3():
    raise Exception(&quot;catch me!&quot;)

set_narration_options(auto_prune=False)

# later, in the same thread:
f1()</code></pre>
<p>Here, we've simply called <code>reset_narration()</code> after the narration text has been acquired, and this gets rid of all fragments for the thread.</p>
<h2 id="errators-operation">Errator's Operation</h2>
<p>Let's look at an example of a set of functions that can be decorated with errator's <code>narrate()</code> decorator. Let's suppose we have a set of functions <code>f1</code> through <code>f6</code>, where <code>f1</code> calls <code>f2</code>, <code>f2</code> calls <code>f3</code>, and so forth. If we stopped in the debugger in <code>f6</code>, Python would report the stack like so:</p>
<table style="width:38%;">
<colgroup>
<col width="11%" />
<col width="26%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">func</th>
<th align="left">execution point</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><blockquote>
<p>f1</p>
</blockquote></td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left"><blockquote>
<p>f2</p>
</blockquote></td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left"><blockquote>
<p>f3</p>
</blockquote></td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left"><blockquote>
<p>f4</p>
</blockquote></td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left"><blockquote>
<p>f5</p>
</blockquote></td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left"><blockquote>
<p>f6</p>
</blockquote></td>
<td align="left">&lt;-- current frame</td>
</tr>
</tbody>
</table>
<p>When we decorate functions with <code>narrate()</code>, additional stack frames are added to the trace; we won't show those here, but instead will show what fragments are managed as the execution progresses. Here's the retained narration fragments if <code>f1..f6</code> are all decorated with <code>narrate()</code> and the current function is <code>f4</code>:</p>
<table style="width:68%;">
<colgroup>
<col width="11%" />
<col width="26%" />
<col width="30%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">func</th>
<th align="left">execution point</th>
<th align="left">fragments for funcs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><blockquote>
<p>f1</p>
</blockquote></td>
<td align="left"></td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left"><blockquote>
<p>f2</p>
</blockquote></td>
<td align="left"></td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left"><blockquote>
<p>f3</p>
</blockquote></td>
<td align="left"></td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left"><blockquote>
<p>f4</p>
</blockquote></td>
<td align="left">&lt;-- current frame</td>
<td align="left">f1, f2, f3, f4</td>
</tr>
<tr class="odd">
<td align="left"><blockquote>
<p>f5</p>
</blockquote></td>
<td align="left"></td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left"><blockquote>
<p>f6</p>
</blockquote></td>
<td align="left"></td>
<td align="left"></td>
</tr>
</tbody>
</table>
<p>When <code>f4</code> returns, the fragments are:</p>
<table style="width:68%;">
<colgroup>
<col width="11%" />
<col width="26%" />
<col width="30%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">func</th>
<th align="left">execution point</th>
<th align="left">fragments for funcs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><blockquote>
<p>f1</p>
</blockquote></td>
<td align="left"></td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left"><blockquote>
<p>f2</p>
</blockquote></td>
<td align="left"></td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left"><blockquote>
<p>f3</p>
</blockquote></td>
<td align="left">&lt;-- current frame</td>
<td align="left">f1, f2, f3</td>
</tr>
<tr class="even">
<td align="left"><blockquote>
<p>f4</p>
</blockquote></td>
<td align="left"></td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left"><blockquote>
<p>f5</p>
</blockquote></td>
<td align="left"></td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left"><blockquote>
<p>f6</p>
</blockquote></td>
<td align="left"></td>
<td align="left"></td>
</tr>
</tbody>
</table>
<p>Note that the fragment for <code>f4</code> is removed.</p>
<p>Now suppose that we have an exception in <code>f6</code>, but the exception isn't captured until <code>f3</code>, at which point the exception is caught and doesn't propagate up the stack any further. This next table shows the fragments present as the functions either return and the exception propagates upward:</p>
<table style="width:68%;">
<colgroup>
<col width="11%" />
<col width="26%" />
<col width="30%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">func</th>
<th align="left">execution point</th>
<th align="left">fragments for funcs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><blockquote>
<p>f1</p>
</blockquote></td>
<td align="left">normal return</td>
<td align="left">f1</td>
</tr>
<tr class="even">
<td align="left"><blockquote>
<p>f2</p>
</blockquote></td>
<td align="left">normal return</td>
<td align="left">f1,f2</td>
</tr>
<tr class="odd">
<td align="left"><blockquote>
<p>f3</p>
</blockquote></td>
<td align="left">exc handled</td>
<td align="left">f1,f2,f3,f4,f5,f6</td>
</tr>
<tr class="even">
<td align="left"><blockquote>
<p>f4</p>
</blockquote></td>
<td align="left">exc passes thru</td>
<td align="left">f1,f2,f3,f4,f5,f6</td>
</tr>
<tr class="odd">
<td align="left"><blockquote>
<p>f5</p>
</blockquote></td>
<td align="left">exc passes thru</td>
<td align="left">f1,f2,f3,f4,f5,f6</td>
</tr>
<tr class="even">
<td align="left"><blockquote>
<p>f6</p>
</blockquote></td>
<td align="left">exception raised</td>
<td align="left">f1,f2,f3,f4,f5,f6</td>
</tr>
</tbody>
</table>
<p>Notice that in <code>f3</code> where the exception is handled we still have all the fragments for all stack frames between the exception origin and the handler, but once the handler returns and errator sees that the exception isn't propagating further it removes the fragments that are no longer useful in narrating an exception (this makes <code>f3</code> a good place to acquire the narration for the exception; more on that later).</p>
<h2 id="capturing-the-narration">Capturing the narration</h2>
<p>Let's repeat the example from earlier, where we said that a function caught an exception and processed it in <code>f3</code>:</p>
<table style="width:68%;">
<colgroup>
<col width="11%" />
<col width="26%" />
<col width="30%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">func</th>
<th align="left">execution point</th>
<th align="left">fragments for funcs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><blockquote>
<p>f1</p>
</blockquote></td>
<td align="left">normal return</td>
<td align="left">f1</td>
</tr>
<tr class="even">
<td align="left"><blockquote>
<p>f2</p>
</blockquote></td>
<td align="left">normal return</td>
<td align="left">f1,f2</td>
</tr>
<tr class="odd">
<td align="left"><blockquote>
<p>f3</p>
</blockquote></td>
<td align="left">exc handled</td>
<td align="left">f1,f2,f3,f4,f5,f6</td>
</tr>
<tr class="even">
<td align="left"><blockquote>
<p>f4</p>
</blockquote></td>
<td align="left">exc passes thru</td>
<td align="left">f1,f2,f3,f4,f5,f6</td>
</tr>
<tr class="odd">
<td align="left"><blockquote>
<p>f5</p>
</blockquote></td>
<td align="left">exc passes thru</td>
<td align="left">f1,f2,f3,f4,f5,f6</td>
</tr>
<tr class="even">
<td align="left"><blockquote>
<p>f6</p>
</blockquote></td>
<td align="left">exception raised</td>
<td align="left">f1,f2,f3,f4,f5,f6</td>
</tr>
</tbody>
</table>
<p>If <code>f3</code> catches the exception, it's probably a good place to grab the exception narration (this isn't required, but it may be a natural place). Suppose <code>f3()</code> looks like the following:</p>
<pre class="sourceCode "><code>@narrate(&quot;While I was running f3&quot;)
def f3():
    try:
        f4()
    except MyException:
        story = get_narration()</code></pre>
<p>In the <code>except</code> clause, we call <code>get_narration()</code> to acquire a list of strings that are the narration for the exception. This will return the entire narration that exists for this call stack; that is, it will give a list of narration fragment strings for <code>f1()</code> through <code>f6()</code>.</p>
<p>But perhaps the whole narration isn't wanted; perhaps all that's desired is the narration for <code>f3()</code> through <code>f6()</code>, as the the narrations before this point actually make the exception narration less clear. You can trim your narration down with by calling <code>get_narration()</code> with the keyword argument <code>from_here</code> set to True:</p>
<pre class="sourceCode "><code>@narrate(&quot;While I was running f3...&quot;)
def f3():
    try:
        f4()
    except MyException:
        story = get_narration(from_here=True)</code></pre>
<p>This will only return the narration strings from the current function to the function that's the source of the exception, in this case <code>f3()</code> through <code>f6()</code>. The <code>from_here</code> argument allows you to control how much narration is returned from <code>get_narration()</code>. It defaults to False, meaning to return the entire narration.</p>
<h2 id="skipping-decorating-functions">Skipping decorating functions</h2>
<p>What happens if you skip decorating some functions in a calling sequence? Nothing much; errator simply won't have anything in it's narration for that function. Below, we indicate a decorated function with an <code>(e)</code> before the function name, and skip decoration of some functions. When we get to <code>f5</code>, the captured fragments are as shown:</p>
<table style="width:68%;">
<colgroup>
<col width="11%" />
<col width="26%" />
<col width="30%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">func</th>
<th align="left">execution point</th>
<th align="left">fragments for funcs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(e)f1</td>
<td align="left"></td>
<td align="left">f1</td>
</tr>
<tr class="even">
<td align="left">(e)f2</td>
<td align="left"></td>
<td align="left">f1,f2</td>
</tr>
<tr class="odd">
<td align="left"><blockquote>
<p>f3</p>
</blockquote></td>
<td align="left"></td>
<td align="left">f1,f2</td>
</tr>
<tr class="even">
<td align="left">(e)f4</td>
<td align="left"></td>
<td align="left">f1,f2,f4</td>
</tr>
<tr class="odd">
<td align="left"><blockquote>
<p>f5</p>
</blockquote></td>
<td align="left">&lt;-- current frame</td>
<td align="left">f1,f2,f4</td>
</tr>
<tr class="even">
<td align="left"><blockquote>
<p>f6</p>
</blockquote></td>
<td align="left"></td>
<td align="left"></td>
</tr>
</tbody>
</table>
<h2 id="customizing-the-narration">Customizing the narration</h2>
<p>Suppose you have a function of several variables:</p>
<pre class="sourceCode "><code>@narrate(&quot;While I was calling f...&quot;)
def f(x, y):
    # do stuff</code></pre>
<p>And a narration with a fixed string doesn't give you enough information as to how the function was called if there was an exception. The <code>narrate()</code> function allows you to supply it with a callable object instead of a string; this callable will be passed all the arguments that were passed to the function and must return a string, which will then be used as the descriptive string for the narration fragment. This function is <strong>only</strong> invoked if the decorated function raises an exception, otherwise it goes uncalled.</p>
<p>Lambdas provide a nice way to specify a function that yields a string:</p>
<pre class="sourceCode "><code>@narrate(lambda a, b: &quot;While I was calling f with x={} and y={}...&quot;.format(a, b))
def f(x, y):
    # do stuff</code></pre>
<p>But you can supply any callable that can cope with the argument list to the decorated function. This allows your narrations to provide more details regarding the calling context of a particular function, since actual argument values can become part of the narration.</p>
<h2 id="getting-more-details-with-contexts">Getting more details with contexts</h2>
<p>It may be the case that narration at the function level isn't granular enough. You may have a lengthy function or one that calls out to other libraries, each of which can raise exceptions of their own. You might be helpful to have narration capabilities at a more granular level to address this.</p>
<p>To support more granular narration, errator provides a context manager that is created with a call to <code>narrate_cm()</code>. This context manager acts similarly to the <code>narrate()</code> decorator. First, a narration fragment is captured when the context is entered. If the context exits &quot;normally&quot; the fragment is discarded. However, if an exception is raised during the context, the fragment is retained as the exception propagates upward.</p>
<p>Suppose we have a function that does two web service calls during its execution, and we'd like to know narration details around each of these activities if any fails in our function. We can use <code>narrate_cm()</code> to achieve this:</p>
<pre class="sourceCode "><code>@narrate(lambda a, b:&quot;So call_em was invoked with x={} and y={}&quot;.format(a, b))
def call_em(x, y):
    # do some stuff to form the first WS call
    with narrate_cm(&quot;...and I started the first web service call...&quot;):
        # do the web service call

    # extract data and do the second call, computing a string named ws2_req
    with narrate_cm(lambda req: &quot;...I started WS call #2 call with {}&quot;.format(req), ws2_req):
        # do the second web service call

    # and whatever else...</code></pre>
<p>This example was constructed to illustrate a couple of uses. Similarly to <code>narrate()</code>, <code>narrate_cm()</code> can be called either with a fixed string, or a callable that returns a string which will be invoked only if there's an exception raised in the context.</p>
<p>The first use of <code>narrate_cm()</code> simply passes a fixed string. If there's an exception during the first web service call, the string is retained, but when reported the string will be indented a few spaces to show that the narration fragment is within the scope of the function's narration.</p>
<p>The second use of <code>narrate_cm()</code> passes a lambda as its callable. But unlike passing a callable to <code>narrate()</code>, you must also supply the arguments to give the callable to <code>narrate_cm()</code>, in this case the local variable ws2_req. This is because the context manager doesn't know what is import relative to the context-- the function arguments or the local variables. You may pass both postional and keyword arguments to <code>narrate_cm()</code>.</p>
<h2 id="advanced-fragment-access">Advanced fragment access</h2>
<p>Errator provides a way to get copies of the actual objects where narration fragments are stored. There are a number of situation where this is useful:</p>
<ul>
<li>if more control over fragment formatting is required</li>
<li>if retention of the details of an error narration is required</li>
<li>you're just that way</li>
</ul>
<p>You can get these objects by using the <code>copy_narration()</code> function. Instead of returning a list of strings like <code>get_narration()</code> does, this function returns a list of <code>NarrationFragment</code> objects which are copies of the objects managed by errator itself. The <code>copy_narration()</code> function takes the same <code>thread</code> and <code>from_here</code> arguments as does <code>get_narration()</code>, so you can control what objects are returned in the same manner. Useful methods on these objects are:</p>
<ul>
<li><code>tell()</code>, which returns a string that is the fragment's part of the overall narration</li>
<li><code>tell_ex()</code>, similar to <code>tell()</code> but provides more contextual information (not fully implemented)</li>
<li><code>fragment_exception_text()</code>, which returns a string that describes the actual exception; really only useful on the last fragment in the call chain</li>
</ul>
<p>Being a lower-level object, you should expect its interface to be a bit more volatile, and should stick with calling <code>tell()</code> if you wish to be isolated from change.</p>
<h2 id="verbose-narrations">Verbose narrations</h2>
<p>The story errator tells is meant to be user-focused; that is, from the perspective of a program's semantics rather than from that of a stack trace. However, there may be circumstances where it would be helpful to have some of the information in a stack trace merged into the rendered narration. Errator supports this with the <code>verbose</code> keyword on the <code>get_narration()</code> function. It defaults to <code>False</code>, but if set to <code>True</code>, then each retrieved narration line will be followed by a line that reports the line number, function, and source file associated with the narration fragment.</p>
<p>Consider this narrated program in a file named verbose.py:</p>
<pre class="sourceCode "><code>from errator import narrate_cm, narrate, get_narration

@narrate(&quot;So I started to &#39;f1&#39;...&quot;)
def f1():
    f2()

@narrate(&quot;...which occasioned me to &#39;f2&#39;&quot;)
def f2():
    with narrate_cm(&quot;during which I started a narration context...&quot;):
        f3()

@narrate(&quot;...and that led me to finally &#39;f3&#39;&quot;)
def f3():
    raise Exception(&quot;oops&quot;)

if __name__ == &quot;__main__&quot;:
    try:
        f1()
    except:
        for l in get_narration(verbose=False):
            print(l)</code></pre>
<p>Which yields the following output when run:</p>
<pre class="sourceCode "><code>So I started to &#39;f1&#39;...
...which occasioned me to &#39;f2&#39;
  during which I started a narration context...
...and that led me to finally &#39;f3&#39;, but exception type: Exception, value: &#39;oops&#39; was raised</code></pre>
<p>If we set <code>verbose=True</code> in the <code>get_narration()</code> call, then the output looks like the following:</p>
<pre class="sourceCode "><code>So I started to &#39;f1&#39;...
    line 5 in f1, /home/tom/errator/docs/verbose.py
...which occasioned me to &#39;f2&#39;
    line 10 in f2, /home/tom/errator/docs/verbose.py
  during which I started a narration context...
       line 10 in f2, /home/tom/errator/docs/verbose.py
...and that led me to finally &#39;f3&#39;, but exception type: Exception, value: &#39;oops&#39; was raised
    line 14 in f3, /home/tom/errator/docs/verbose.py</code></pre>
<p>...thus letting you see the actual lines being executed when the exception is raised.</p>
<h2 id="testing-and-debugging">Testing and debugging</h2>
<p>As errator is meant to help you make sense when something goes wrong, it would be a shame if something went wrong while errator was doing its thing. But since errator users can supply a callable to <code>narrate()</code> and <code>narrate_cm()</code>, there's the possibility that an error lurks in the callable itself, and errator could raise an exception in trying to tell you about an exception. Worse, if there is a bug in a callable, you'd only know about it if an exception is raised, which may be difficult to force in testing, or may escape testing and only show up in production.</p>
<p>To help you find problems earlier, errator provides an option that changes the rules regarding when fragments, and hence callables, are formatted. By adding:</p>
<pre class="sourceCode "><code>set_default_options(check=True)</code></pre>
<p>Before entering an errator decorated function or managed context, you inform errator that you wish to check the generation of every narration fragment, whether there's been an exception raised or not. You can also set the 'check' option on an existing narration's thread with:</p>
<pre class="sourceCode "><code>set_narration_options(check=True)</code></pre>
<p>which will set fragment checking only for the current thread's narration (or the thread named with the <code>thread=</code> argument; see the documentation for <code>set_narration_options()</code> for details).</p>
<p>When the <code>check</code> option is True, every time a decorated function returns or a managed context exits, errator formats the narration fragment, including calling any callable supplied to exercise the code it refers to. By setting check to True in your testing code, you can be sure that every narration fragment is generated, and hence every callable for a fragment is invoked. This helps you ensure that you have the correct number of arguments to your callable and raises confidence that the callable will operate correctly in a real exception situation (this isn't a guarantee, however, as the conditions that raise an exception my be different from those in testing).</p>
<blockquote>
<p><strong>note</strong></p>
<p>You don't want to run production code with <code>check</code> set to True (it defaults to False). This is because doing so incurs the execution time of every callable where the check==True applies, which can have significant performance impact on your code. Errator normally only invokes the callable if there's an exception, thus sparing your code from the call overhead and extra execution time. So be sure not have the check option set True in production.</p>
</blockquote>
<h2 id="tidying-up-stack-traces">Tidying up stack traces</h2>
<p>Errator's <code>narrate()</code> decorator wraps the function being decorated, which means that if you use the various stack and traceback reporting functions in the standard <code>traceback</code> module, you can get materially longer traces than you'd otherwise like. If you'd rather not see these, errator supplies a set of wrapper functions that are analogs of the functions in <code>traceback</code> that strip out the errator calls from returned objects or printed stack traces. These functions are all argument-compatible with the functions in <code>traceback</code>. Specifically, errator provides analogs to:</p>
<ul>
<li>extract_tb</li>
<li>extract_stack</li>
<li>format_tb</li>
<li>format_stack</li>
<li>format_exception_only</li>
<li>format_exception</li>
<li>print_tb</li>
<li>print_exception</li>
<li>print_exc</li>
<li>format_exc</li>
<li>print_last</li>
<li>print_stack</li>
</ul>
<p>...all of which remove traces of errator from the output.</p>
<h2 id="usage-tips">Usage tips</h2>
<ul>
<li>When decorating a method with <code>narrate()</code> and supplying a callable, don't forget to include the <code>self</code> argument in the callable's argument list.</li>
<li>Decorating generator functions gives unexpected results; the function will return immediately with the generator as the value, hence the narration fragment will not be retained. If you wish to get narration for generator functions, you need to use the <code>narrate_cm()</code> context manager within the generator to accomplish this.</li>
<li>At the moment, behavior with coroutines has not been investigated, but almost certainly the current release will do surprising things. This will need further investigation.</li>
</ul>
